apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "simple-app-helm.fullname" . }}
  labels:
    {{- include "simple-app-helm.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "simple-app-helm.fullname" . }}
    weight: 100
  wildcardPolicy: None