apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app.kubernetes.io/name: simple-app 
    app.kubernetes.io/instance: simple-app
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-app
      app.kubernetes.io/instance: simple-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-app
        app.kubernetes.io/instance: simple-app
    spec:
      containers:
        - name: simple-app
          image: "quay.io/rht-lafuse-at-extraordy/simple-app:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: GIN_MODE
            value: "debug"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healtz
              port: http
          readinessProbe:
            httpGet:
              path: /healtz
              port: http