apiVersion: v1
kind: Service
metadata:
  name: simple-app
  labels:
    app.kubernetes.io/name: simple-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    deployment: simple-app
