apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: simple-app
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
